### ISSUE TITLE
winget support

### ISSUE THREAD

**Issue by alanlivio** [BtbN/FFmpeg-Builds#194]
It should be interesting support to install winget.
Expected scenario:

```
winget install BtbN.ffmpeg
```

More info at:
- https://github.com/microsoft/winget-cli
- https://github.com/microsoft/winget-pkgs
- https://docs.microsoft.com/en-us/windows/package-manager/

**Comment by BtbN** [comment]
I don't really see a realistic way to do this.
The way I understand their workflow, I'd have to automatically send them a PR every single day with the latest version, and hope they merge it in any kind of reasonable timeframe?
That doesn't really seem practical, and they'd probably make me stop sooner or later as well.

**Comment by alanlivio** [comment]
Many thanks. If misunderstood that you didn't see it worthy. Best,

**Comment by loscrossos** [comment]
it would be great to have your package in winget!

you dont have to send daily updates. i think you could tag your builds daily but only make a "release" once a month or trigger the winget-uploader github action once a month or when ffmpeg makes a releae:

https://www.ffmpeg.org/download.html#releases

winget releases are actually ultra easy specially for CLI tools in zip like ffmpeg. the whole manifesto is like 20 lines. the winget framework does all the work for you!

you say:
-name and version of the package: winget publishes it.
-declare it a zip file and that its portable: it means it does not need installation only unzip (winget does all this in the approtiate folder depending if the user requested per-user or whole system install)
-say which are the relevant exe files (ffmpeg, ffprobe, ffplay): winget will create symlinks in a directory on the path.

-declare that its a CLI tool with dlls (instead of a single exe): (ArchiveBinariesDependOnPath: true): the installer will make the bin folder available on the windows path

-say where to download the zip: the perma-url of your zip.

thats what is in the yaml of gyans ffmpeg(plus 2 translation files):

https://github.com/microsoft/winget-pkgs/blob/master/manifests/g/Gyan/FFmpeg/Shared/7.1.1/Gyan.FFmpeg.Shared.installer.yaml



winget generates the installer and the entries with a github action that triggers the make script and uploads the yaml definition ((example from terminal project)

https://github.com/microsoft/terminal/blob/main/.github/workflows/winget.yml

**Comment by BtbN** [comment]
The problem is, it's not just the FFmpeg version, but the version of several dozen dependencies as well.
So publishing a package just called "FFmpeg Version X" is a bit misleading, since I could build that same FFmpeg version again next week, but with a whole new updated set of dependencies, that potentially fix critical vulnerabilities. Like, when the bundled OpenSSL version had a round of critical updates for example.

So I'd need to do something like publish a package weekly or something via automated pull request.

**Comment by loscrossos** [comment]
im not sure if i understood your concern correctly.
You dont do much of PR to winget. In fact apart from publishing a 20 liner to winget you would not do anything different from what you do today:

On Winget Repo: you just basically upload a small 20-line file telling your new Version number  and the path to download it. I think as long as the file is valid yaml they dont do any checking apart from formally bot checks that the URL of your zip is valid. Even if your build is broken, as long as the zip exists the publication would be accepted as long as the yaml is valid. Winget would create versions, yaml directory and all.

The work happens on user side anyway: User asks for your yaml and on his machine the winget.exe does the installing n stuff. 

So all you do is setup a weekly github action that creates that yaml.

winget takes care of packaging, publishing and even marketing as people can just do what i do: google "winget ffmpeg" and take one of the many results pointing to available packages.

As for the version:

my understanding is that its clear that this would not be "the" Ffmpeg 7.1 but  your package. Also Versioning takes care of the issues you mention:

this would be your flavor. Just as there isnt "the" linux but Ubuminfedusehat Linux :)

just as Gyan; He has his FFmpeg flavor in 2 sub-flavors:

`https://winstall.app/apps/Gyan.FFmpeg.Shared` (shared)

`https://winstall.app/apps/Gyan.FFmpeg` (static)

thats how you install it in windows as well:

`winget install --id=Gyan.FFmpeg  -e`

`winget install --id=Gyan.FFmpeg.Shared  -e`


and his versios are called:

```
ffmpeg
ffmpeg version 7.1.1-full_build-www.gyan.dev Copyright (c) 2000-2025 the FFmpeg developers
  built with gcc 14.2.0 (Rev1, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 [....]
```

he has a main 7.1.1 that is published to wionget as main release  and  nightlys that are not pushed to winget.

so i would think you can call your package:

`BtbN.FFmpeg`

and your version something like:

`ffmpeg version 7.1.1.ge73c59c6c3-20250425"

which you do anyway today (except the 7.1.1).

that way its clear to anyone that its your build (which vastly differs from Gyans in configuration and is the reason i think your build would be a great addition to winget!), which major version from FFmpeg it comes from and also which exact daily build and patch its built from for traceability on your repo.

and *even* if you want you can publish nightly packages! even mozilla has a nightly winget package:

https://winget.run/search?query=nightly

Winget themselves, they dont care, since on their end a "version" is just 20 lines of yaml code defining the version and where to download it. yt-dlp.yt has regular versions (for people who dont want daily updates) and nightly packages:

https://github.com/microsoft/winget-pkgs/tree/master/manifests/y/yt-dlp/yt-dlp/nightly/

so a full workkflow is:

1. build package
2. create release on github
3. create and push yaml to winget repo

Gyan builds and hosts outside of github. his github account is only there so he can upload his releases so that they are available for winget. You do everything natively in winget from the get-go.


looking forward to:

`winget install --id=BtbN.FFmpeg.Shared  -e`

:)

**Comment by SpecterShell** [comment]
In case you don't know: `BtbN.FFmpeg.*` has been available in the [winget-pkgs](https://github.com/microsoft/winget-pkgs) repo...for one year!

Only the monthly version is available though.

**Comment by SCIEN-00** [comment]
Hei!
Would be nice to include also ARM64 architecture in manifest file. Should look something like this then.
```yaml
# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: BtbN.FFmpeg.GPL.8.0
PackageVersion: 8.0-20251031
InstallerType: zip
NestedInstallerType: portable
Commands:
  - ffmpeg
  - ffplay
  - ffprobe
ReleaseDate: 2025-10-31
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2025-10-31-13-40/ffmpeg-n8.0-30-g71007e6c12-win64-gpl-8.0.zip
    InstallerSha256: 05ECC01BB03EF1F4D908C3C982512F07F888848429BE6E9662A5A7C558C60B4F
    NestedInstallerFiles:
      - RelativeFilePath: ffmpeg-n8.0-30-g71007e6c12-win64-gpl-8.0\bin\ffmpeg.exe
        PortableCommandAlias: ffmpeg
      - RelativeFilePath: ffmpeg-n8.0-30-g71007e6c12-win64-gpl-8.0\bin\ffplay.exe
        PortableCommandAlias: ffplay
      - RelativeFilePath: ffmpeg-n8.0-30-g71007e6c12-win64-gpl-8.0\bin\ffprobe.exe
        PortableCommandAlias: ffprobe
  - Architecture: arm64
    InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2025-10-31-13-40/ffmpeg-n8.0-30-g71007e6c12-winarm64-gpl-8.0.zip
    InstallerSha256: 5276AF84B736B279A70514C5B7E236F03961AB5517D911A88371838459B94C40
    NestedInstallerFiles:
      - RelativeFilePath: ffmpeg-n8.0-30-g71007e6c12-winarm64-gpl-8.0\bin\ffmpeg.exe
        PortableCommandAlias: ffmpeg
      - RelativeFilePath: ffmpeg-n8.0-30-g71007e6c12-winarm64-gpl-8.0\bin\ffplay.exe
        PortableCommandAlias: ffplay
      - RelativeFilePath: ffmpeg-n8.0-30-g71007e6c12-winarm64-gpl-8.0\bin\ffprobe.exe
        PortableCommandAlias: ffprobe

ManifestType: installer
ManifestVersion: 1.10.0
```
