### ISSUE TITLE
Debug build

### ISSUE THREAD

**Issue by miltontaylor-panotek** [BtbN/FFmpeg-Builds#340]
Am trying to get a debug build of this through a github  action, using a fork of this repo...

I made a copy of the build.yml file and reduced it down to just do a win64 build of nonfree-shared and it does that fine.  However for the life of me I cannot get it to build the debug variant.

This is what I tried most recently, but the release it produced seemed to be the same as the normal one - there were no pdb files in the zip.  Also could not quite work out how to specify both debug and 6.1 together... seems the bit that does the image management is not expecting a combo of three variant codes like this: [nonfree-shared 6.1 debug]

```
  build_ffmpeg:
    name: Build ffmpeg
    if: ${{ ( github.event.inputs.buildOnly == 'true' && !cancelled() ) || success() }}
    needs: build_targets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [win64]
        variant: [nonfree-shared debug]
```
